services:
  cards-app:
    build:  
      context: .
      dockerfile: Dockerfile
    image: cards-app-prod
    container_name: cards-app
    restart: unless-stopped
    env_file:              
      - .env

    ports:                 
      - "3000:3000"
